#!/usr/bin/env bash
# install-headscale.sh
#
# Installs and configures a Headscale server on the VPS.
#
# Headscale is a self-hosted, open-source implementation of the Tailscale
# control server. This script installs the latest Headscale release from
# GitHub, writes a production-ready configuration, opens the required firewall
# ports via ufw, starts the systemd service, and creates the Headscale user
# that all devices will register under.
#
# Compatible with: Headscale v0.23 and later, Debian/Ubuntu.
#
# Prerequisites:
#   - A Debian/Ubuntu system with apt and dpkg available.
#   - Running as root (or with sudo).
#   - DNS A record headscale.perdrizet.org already pointing to this VPS.
#     Let's Encrypt will attempt an HTTP-01 challenge on port 80 to issue the
#     TLS certificate; the record must resolve correctly before first start.
#
# Usage:
#   sudo bash scripts/install-headscale.sh
#
# After this script completes, register each device with:
#   headscale nodes register --user siderealyear --key <nodekey>
# or use a pre-auth key (see docs/manual-steps.md).

set -euo pipefail

# --- Configuration -----------------------------------------------------------

# The public URL at which Tailscale clients will reach this control server.
SERVER_URL='https://headscale.perdrizet.org'

# The base domain used for MagicDNS hostnames (e.g. laptop.perdrizet.org).
BASE_DOMAIN='perdrizet.org'

# Optional: set to an email address to receive Let's Encrypt expiry notices.
ACME_EMAIL='siderealyear@headscale.perdrizet.org'

# The Headscale user that all devices in this tailnet will belong to.
HEADSCALE_USER='siderealyear'

# --- Helper functions --------------------------------------------------------

log() {
    echo "[install-headscale] $*"
}

die() {
    echo "[install-headscale] ERROR: $*" >&2
    exit 1
}

# --- Pre-flight checks -------------------------------------------------------

[[ $EUID -eq 0 ]] || die 'This script must be run as root. Use: sudo bash scripts/install-headscale.sh'

command -v curl &>/dev/null  || die 'curl is required but not installed. Run: apt-get install -y curl'
command -v dpkg &>/dev/null  || die 'dpkg not found. This script requires a Debian/Ubuntu system.'
command -v ufw  &>/dev/null  || die 'ufw not found. Install it with: apt-get install -y ufw'

# --- Detect the latest Headscale release -------------------------------------

log 'Detecting the latest Headscale release from GitHub...'

HEADSCALE_VERSION=$(
    curl -fsSL https://api.github.com/repos/juanfont/headscale/releases/latest \
    | grep '"tag_name"' \
    | sed 's/.*"v\([^"]*\)".*/\1/'
)

[[ -n "$HEADSCALE_VERSION" ]] \
    || die 'Failed to detect Headscale version. Check network connectivity and the GitHub API.'

log "Latest Headscale version: v${HEADSCALE_VERSION}"

# --- Download and install the .deb package -----------------------------------

ARCH=$(dpkg --print-architecture)

log "Downloading headscale_${HEADSCALE_VERSION}_linux_${ARCH}.deb..."

curl -fsSL \
    -o /tmp/headscale.deb \
    "https://github.com/juanfont/headscale/releases/download/v${HEADSCALE_VERSION}/headscale_${HEADSCALE_VERSION}_linux_${ARCH}.deb"

log 'Installing package...'

apt-get install -y /tmp/headscale.deb

rm -f /tmp/headscale.deb

log "Headscale v${HEADSCALE_VERSION} installed."

# --- Write the configuration file --------------------------------------------

log 'Writing /etc/headscale/config.yaml...'

mkdir -p /etc/headscale

# The heredoc uses unquoted EOF so that shell variables (SERVER_URL,
# BASE_DOMAIN, ACME_EMAIL) are substituted. All other content is static YAML.
cat > /etc/headscale/config.yaml <<EOF
# Headscale configuration
# Generated by scripts/install-headscale.sh
# Compatible with Headscale v0.23 and later.

# The public URL at which Tailscale clients reach this control server.
server_url: ${SERVER_URL}

# Listen on all interfaces on port 443.
# TLS is managed by the built-in Let's Encrypt ACME integration below.
listen_addr: 0.0.0.0:443

# Prometheus metrics endpoint, accessible only from localhost.
metrics_listen_addr: 127.0.0.1:9090

# gRPC endpoint used when calling the headscale CLI with --address.
# The CLI defaults to the unix socket below, so this is only needed for
# remote CLI access.
grpc_listen_addr: 127.0.0.1:50443
grpc_allow_insecure: false

# Key files are generated automatically on first start.
private_key_path: /var/lib/headscale/private.key
noise:
  private_key_path: /var/lib/headscale/noise_private.key

# IP address ranges assigned to nodes on the tailnet.
# Note: the format changed in Headscale v0.23 from a list (ip_prefixes) to a
# map with explicit v4/v6 keys. The allocation strategy controls how IPs are
# assigned: "sequential" assigns the next available address in order.
prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48
  allocation: sequential

# DERP relay configuration.
# The embedded DERP server is disabled. Tailscale's public DERP map is used
# as the fallback relay when a direct WireGuard connection cannot be made.
derp:
  server:
    enabled: false
    region_id: 999
    region_code: "headscale"
    region_name: "Headscale Embedded DERP"
    stun_listen_addr: "0.0.0.0:3478"
  urls:
    - https://controlplane.tailscale.com/derpmap/default
  auto_update_enabled: true
  update_frequency: 24h

# SQLite database for storing node state and configuration.
database:
  type: sqlite
  sqlite:
    path: /var/lib/headscale/db.sqlite

# TLS certificate via Let's Encrypt using the HTTP-01 challenge.
# Let's Encrypt will make an HTTP request to port 80 to verify domain
# ownership. Port 80 must be reachable from the public internet.
acme_url: https://acme-v02.api.letsencrypt.org/directory
acme_email: "${ACME_EMAIL}"
tls_letsencrypt_hostname: headscale.perdrizet.org
tls_letsencrypt_cache_dir: /var/lib/headscale/cache
tls_letsencrypt_challenge_type: HTTP-01
tls_letsencrypt_listen: ":80"

# Log format and verbosity.
log:
  format: text
  level: info

# MagicDNS configuration.
# Devices will be reachable at <hostname>.perdrizet.org once MagicDNS is
# enabled. The hostname used is each device's system hostname at registration.
dns:
  magic_dns: true
  base_domain: ${BASE_DOMAIN}
  nameservers:
    global:
      - 1.1.1.1
      - 1.0.0.1
  override_local_dns: true
  domains: []
  search_domains: []

# Remove ephemeral nodes (registered with --ephemeral) after this period of
# inactivity.
ephemeral_node_inactivity_timeout: 30m

# How often the server checks for node updates.
node_update_check_interval: 10s

# Suppress update-available notifications in logs.
disable_check_updates: false

# Unix socket used by the headscale CLI on this machine.
unix_socket: /var/run/headscale/headscale.sock
unix_socket_permission: "0770"
EOF

log 'Configuration written to /etc/headscale/config.yaml.'

# --- Configure ufw firewall rules --------------------------------------------

log 'Configuring ufw firewall rules...'

# Port 80 is required for the Let's Encrypt HTTP-01 ACME challenge.
ufw allow 80/tcp  comment 'Headscale ACME HTTP-01 challenge'

# Port 443 is the main Headscale HTTPS listener.
ufw allow 443/tcp comment 'Headscale HTTPS'

# Port 3478 is the STUN port used for NAT traversal hole-punching.
ufw allow 3478/udp comment 'Tailscale STUN'

# Port 41641 is the WireGuard UDP port for direct Tailscale connections.
ufw allow 41641/udp comment 'Tailscale WireGuard'

log 'Firewall rules added.'

# --- Enable and start the Headscale service ----------------------------------

log 'Enabling and starting the headscale systemd service...'

systemctl enable headscale
systemctl restart headscale

# Give the process a moment to start before checking its status.
sleep 3

systemctl is-active --quiet headscale \
    || die 'Headscale failed to start. Inspect the logs with: journalctl -u headscale -n 50'

log 'Headscale service is running.'

# --- Create the Headscale user -----------------------------------------------

log "Creating Headscale user '${HEADSCALE_USER}'..."

# Check whether the user already exists to make this step idempotent.
if headscale users list 2>/dev/null | grep -qw "${HEADSCALE_USER}"; then
    log "User '${HEADSCALE_USER}' already exists, skipping creation."

else
    headscale users create "${HEADSCALE_USER}"
    log "User '${HEADSCALE_USER}' created."
fi

# --- Done --------------------------------------------------------------------

log ''
log 'Headscale installation complete.'
log ''
log "  Control server : ${SERVER_URL}"
log "  Headscale user : ${HEADSCALE_USER}"
log ''
log 'Next steps:'
log '  1. Verify the service: systemctl status headscale'
log '  2. Inspect logs if needed: journalctl -u headscale -f'
log '  3. On each client device, run: sudo bash scripts/install-tailscale-client.sh'
log '  4. Approve each node: headscale nodes register --user siderealyear --key <nodekey>'
log '     Or use a pre-auth key -- see docs/manual-steps.md for details.'
