# Root domain redirect
# Domain: perdrizet.org -> logkeep.perdrizet.org

# HTTP
server {
    if ($host = www.perdrizet.org) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = perdrizet.org) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name perdrizet.org www.perdrizet.org;
    include snippets/security-headers.conf;

    return 301 https://logkeep.perdrizet.org$request_uri;




}

# HTTPS
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name perdrizet.org www.perdrizet.org;
    include snippets/security-headers.conf;

    # SSL Configuration - Ionos Wildcard Certificate
    ssl_certificate /etc/letsencrypt/live/gpt.perdrizet.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/gpt.perdrizet.org/privkey.pem; # managed by Certbot
    
    # SSL Protocols
    ssl_protocols TLSv1.2 TLSv1.3;
    
    # Redirect to main application
    return 301 https://logkeep.perdrizet.org$request_uri;


}
